### ISSUE TITLE
Replace map tags with image that links to Hitchmap

### ISSUE THREAD

**Issue by bopjesvla** [Hitchwiki/hitchwiki#214]
Here's a library that creates a lil map:

https://github.com/bopjesvla/tiny-static-map

Here's a script that replaces all map tags with lil maps:

```
document.addEventListener("DOMContentLoaded", function() {
    // Find all map elements in the document
    const mapElements = document.querySelectorAll("map[lat][lng][zoom]");

    mapElements.forEach((mapElement) => {
        // Extract the map attributes
        const lat = parseFloat(mapElement.getAttribute("lat"));
        const lon = parseFloat(mapElement.getAttribute("lng"));
        const zoom = parseInt(mapElement.getAttribute("zoom"), 10);
        const width = 300; // Set width for the static map display
        const height = 300; // Set height for the static map display
        
        // Create a container div for the static map
        const mapContainer = document.createElement("div");

        // Call the function to create the static map inside the container
        createStaticMap(mapContainer, lat, lon, zoom, width, height);

        // Create an anchor element that wraps the map container
        const mapLink = document.createElement("a");
        mapLink.href = `https://hitchmap.com/#location,${lat},${lon},${zoom}`;
        mapLink.appendChild(mapContainer);

        // Replace the original <map> element with the link containing the map container
        mapElement.replaceWith(mapLink);
    });
});
```

And this is what ChatGPT has to say about allowing the map tag:

To allow a new HTML tag on a wiki, the process generally depends on the wiki software you're using. Here’s a basic guide for some popular wiki platforms:
1. MediaWiki

    Configuration File: In MediaWiki, allowed HTML tags are controlled through the AllowedHTML configuration variable. To add tags, you can modify this variable in the LocalSettings.php file.
    Steps:
        Open the LocalSettings.php file in your MediaWiki installation.
        Add or modify the $wgAllowHTMLElements variable to include the tags you want to allow:

    $wgAllowHTMLElements[] = 'newtag';

    Replace newtag with the HTML tag you want to add, e.g., iframe, video, etc.
    Save the changes and clear the cache if needed.

**Comment by guaka** [comment]
Added code to https://hitchwiki.org/en/MediaWiki:Common.js but got `JavaScript parse error: Parse error: Missing ) in parenthetical in file 'MediaWiki:Common.js' on line 15`

Gave you admin and bureaucrat rights so you can change this page, and thus the JS that is on hitchwiki.org

Note, I tried this at https://hitchwiki.org/en/Berlin

**Comment by guaka** [comment]
https://hitchwiki.org/en/MediaWiki:Common.css could also be useful for this

**Comment by bopjesvla** [comment]
I can't seem to edit common.js yet:

```
You do not have permission to edit this page, for the following reason:

You do not have permission to edit this JavaScript page because it may affect all visitors.

Permissions for editing of sitewide CSS/JS/JSON files were recently separated from the editinterface right. If you do not understand why you are getting this error, see [mw:MediaWiki_1.32/interface-admin](https://hitchwiki.org/en/index.php?title=Mw:MediaWiki_1.32/interface-admin&action=edit&redlink=1).
```

I do have the roles you named.

As for the error, I suspect the code minifier in the wiki might be outdated and unable to understand arrow functions. Also, we do need to include the tiny-static-map library. It's so tiny it can be embedded in the code:

```
async function createStaticMap(mapContainer, lat, lon, zoom, width, height) {const TILE_SIZE = 256; const centerX = ((lon + 180) / 360) * Math.pow(2, zoom) * TILE_SIZE; const centerY = ((1 - Math.log(Math.tan(lat * Math.PI / 180) + 1 / Math.cos(lat * Math.PI / 180)) / Math.PI) / 2) * Math.pow(2, zoom) * TILE_SIZE; const topLeftX = centerX - width / 2, topLeftY = centerY - height / 2; const startTileX = Math.floor(topLeftX / TILE_SIZE), startTileY = Math.floor(topLeftY / TILE_SIZE); const xOffset = -(topLeftX % TILE_SIZE), yOffset = -(topLeftY % TILE_SIZE); const xTiles = Math.ceil(width / TILE_SIZE) + 1, yTiles = Math.ceil(height / TILE_SIZE) + 1; mapContainer.style.cssText = `width:${width}px;height:${height}px;position:relative;overflow:hidden`; for (let x = 0; x < xTiles; x++) {for (let y = 0; y < yTiles; y++) {const img = document.createElement("img"); img.src = `https://tile.openstreetmap.org/${zoom}/${startTileX + x}/${startTileY + y}.png`; img.style.cssText = `position:absolute;width:${TILE_SIZE}px;height:${TILE_SIZE}px;left:${(x * TILE_SIZE) + xOffset}px;top:${(y * TILE_SIZE) + yOffset}px`; mapContainer.appendChild(img);}}}

var mapbox = document.querySelector('.infobox-map')

function findFloatAttr(attr) {
     let floatRegex = /\d+(\.\d+)?/
     return +mapbox.innerText.split(attr)[1].match(floatRegex)[0]
}

// Extract the map attributes
var lat = findFloatAttr("lat");
var lon = findFloatAttr("lng");
var zoom = findFloatAttr("zoom");
var width = 300; // Set width for the static map display
var height = 300; // Set height for the static map display

// Create a container div for the static map
var mapContainer = document.createElement("div");

// Call the function to create the static map inside the container
createStaticMap(mapContainer, lat, lon, zoom, width, height);

// Create an anchor element that wraps the map container
var mapLink = document.createElement("a");
mapLink.href = `https://hitchmap.com/#location,${lat},${lon},${zoom}`;
mapLink.appendChild(mapContainer);

// Replace the original <map> element with the link containing the map container
mapbox.innerHTML = '';
mapbox.appendChild(mapLink);
```

**Comment by bopjesvla** [comment]
The above should work without reallowing map as an HTML tag

**Comment by guaka** [comment]
you're now also an "interface administrator", this could be the role required, wanna try again?

**Comment by bopjesvla** [comment]
Thanks, got it working on desktop!

The parser is indeed quite old, the trick was to ask ai to rewrite the script for legacy parsers.

common.js does not seem to be run on mobile, possibly because of this error that occurs exclusively on mobile and also occurs when common.js is entirely empty:

```
[98fea403906f94bdfa3d7ccc] /en/load.php?debug=false&lang=en&modules=ext.dismissableSiteNotice%7Cjquery%2Coojs%2Coojs-router%7Cjquery.accessKeyLabel%2Cclient%2Ccookie%2Cthrottle-debounce%7Cmediawiki.RegExp%2CString%2CTitle%2CUri%2Capi%2Cbase%2Ccldr%2Cexperiments%2CjqueryMsg%2Clanguage%2Cnotify%2Crouter%2Cstorage%2Ctemplate%2Cuser%2Cutil%2Cviewport%7Cmediawiki.libs.pluralruleparser%7Cmediawiki.page.startup%7Cmediawiki.template.hogan%2Cregexp%7Cmediawiki.ui.input%7Cmobile.ajax.styles%7Cmobile.editor.api%7Cmobile.init%2Creferences%2Csearch%2Csite%2Cstartup%2Ctoggle%2Cwatchstar%7Cmobile.pagelist.scripts%2Cstyles%7Cmobile.pagesummary.styles%7Cmobile.references.gateway%2Cimages%7Cmobile.search.api%2Cimages%2Cutil%7Cmobile.site.styles%7Cmobile.startup.images%7Cmobile.startup.images.variants%7Cskins.minerva.editor%2CmainMenu%2Coptions%2Cscripts%2Ctalk%2Ctoggling%2Cwatchstar%7Cskins.minerva.icons.images.scripts%2Cvariants%7Cskins.minerva.icons.images.scripts.misc%7Cskins.minerva.icons.page.issues.default.color%7Cskins.minerva.icons.page.issues.medium.color%7Cskins.minerva.icons.page.issues.uncolored%7Cskins.minerva.mainMenu.icons%2Cstyles%7Cskins.minerva.options.share.icon%7Cskins.minerva.scripts.top%7Cuser.defaults&skin=minerva&version=1ji1pod   MWException from line 804 of /var/www/hitchwiki/htdocs/wiki/includes/resourceloader/ResourceLoaderFileModule.php: ResourceLoaderFileModule::readScriptFiles: script file not found: "/var/www/hitchwiki/htdocs/wiki/extensions/MobileFrontend/resources/dist/mediawiki.template.hogan.js"
Backtrace:
#0 /var/www/hitchwiki/htdocs/wiki/includes/resourceloader/ResourceLoaderFileModule.php(353): ResourceLoaderFileModule->readScriptFiles()
#1 /var/www/hitchwiki/htdocs/wiki/includes/resourceloader/ResourceLoaderModule.php(708): ResourceLoaderFileModule->getScript()
#2 /var/www/hitchwiki/htdocs/wiki/includes/resourceloader/ResourceLoaderModule.php(675): ResourceLoaderModule->buildContent()
#3 /var/www/hitchwiki/htdocs/wiki/includes/resourceloader/ResourceLoader.php(1072): ResourceLoaderModule->getModuleContent()
#4 /var/www/hitchwiki/htdocs/wiki/includes/resourceloader/ResourceLoader.php(776): ResourceLoader->makeModuleResponse()
#5 /var/www/hitchwiki/htdocs/wiki/load.php(51): ResourceLoader->respond()
#6 {main}

[98fea403906f94bdfa3d7ccc] /en/load.php?debug=false&lang=en&modules=ext.dismissableSiteNotice%7Cjquery%2Coojs%2Coojs-router%7Cjquery.accessKeyLabel%2Cclient%2Ccookie%2Cthrottle-debounce%7Cmediawiki.RegExp%2CString%2CTitle%2CUri%2Capi%2Cbase%2Ccldr%2Cexperiments%2CjqueryMsg%2Clanguage%2Cnotify%2Crouter%2Cstorage%2Ctemplate%2Cuser%2Cutil%2Cviewport%7Cmediawiki.libs.pluralruleparser%7Cmediawiki.page.startup%7Cmediawiki.template.hogan%2Cregexp%7Cmediawiki.ui.input%7Cmobile.ajax.styles%7Cmobile.editor.api%7Cmobile.init%2Creferences%2Csearch%2Csite%2Cstartup%2Ctoggle%2Cwatchstar%7Cmobile.pagelist.scripts%2Cstyles%7Cmobile.pagesummary.styles%7Cmobile.references.gateway%2Cimages%7Cmobile.search.api%2Cimages%2Cutil%7Cmobile.site.styles%7Cmobile.startup.images%7Cmobile.startup.images.variants%7Cskins.minerva.editor%2CmainMenu%2Coptions%2Cscripts%2Ctalk%2Ctoggling%2Cwatchstar%7Cskins.minerva.icons.images.scripts%2Cvariants%7Cskins.minerva.icons.images.scripts.misc%7Cskins.minerva.icons.page.issues.default.color%7Cskins.minerva.icons.page.issues.medium.color%7Cskins.minerva.icons.page.issues.uncolored%7Cskins.minerva.mainMenu.icons%2Cstyles%7Cskins.minerva.options.share.icon%7Cskins.minerva.scripts.top%7Cuser.defaults&skin=minerva&version=1ji1pod   MWException from line 804 of /var/www/hitchwiki/htdocs/wiki/includes/resourceloader/ResourceLoaderFileModule.php: ResourceLoaderFileModule::readScriptFiles: script file not found: "/var/www/hitchwiki/htdocs/wiki/extensions/MobileFrontend/resources/dist/mobile.startup.runtime.js"
Backtrace:
#0 /var/www/hitchwiki/htdocs/wiki/includes/resourceloader/ResourceLoaderFileModule.php(353): ResourceLoaderFileModule->readScriptFiles()
#1 /var/www/hitchwiki/htdocs/wiki/includes/resourceloader/ResourceLoaderModule.php(708): ResourceLoaderFileModule->getScript()
#2 /var/www/hitchwiki/htdocs/wiki/includes/resourceloader/ResourceLoaderModule.php(675): ResourceLoaderModule->buildContent()
#3 /var/www/hitchwiki/htdocs/wiki/includes/resourceloader/ResourceLoader.php(1072): ResourceLoaderModule->getModuleContent()
#4 /var/www/hitchwiki/htdocs/wiki/includes/resourceloader/ResourceLoader.php(776): ResourceLoader->makeModuleResponse()
#5 /var/www/hitchwiki/htdocs/wiki/load.php(51): ResourceLoader->respond()
```

**Comment by guaka** [comment]
It might help if I upgrade mediawiki... #37 

nomadwiki is on latest MW, so I have a little more courage to upgrade hitchwiki, makes sense to first do trashwiki

**Comment by guaka** [comment]
Doesn't seem to work on all articles on desktop yet, e.g. https://hitchwiki.org/en/B%C3%B6rde_S%C3%BCd

**Comment by tillwenke** [comment]
also https://hitchwiki.org/en/United_States_of_America shows China for me

**Comment by tillwenke** [comment]
Can we maybe get smth saying... like "Click the map for hitchmap/ hitchhiking spots"?

**Comment by guaka** [comment]
started adding `{{geo-incorrect}}` to articles where the map is not correct, like the US

here's a list https://hitchwiki.org/en/Special:WhatLinksHere/Template:Geo-incorrect

not sure if the problem is with incorrect latlng values or with hitchmap

**Comment by guaka** [comment]
Could be that `lat='38.69087' lng='-9.126892'` shows up as `lat='38.69087' lng='9.126892'`, so lat > 0 instead of < 0

**Comment by bopjesvla** [comment]
Missed this discussion, think I fixed it

**Comment by tillwenke** [comment]
can be closed imo
